export const restaurants = [
  {
    id: 1,
    city: "Paris",
    image: "/res_1.png",
    people: "2 people",
    cuisine: "Italian",
    price: "$$",
    category: "Green Oasis",
    name: "Le Chat Blanc",
    date: "Sat, Jun 25, 17:00",
  },
  {
    id: 2,
    city: "Paris",
    image: "/res_2.png",
    people: "2 people",
    cuisine: "Italian",
    price: "$$$",
    category: "Trendy",
    name: "Le Maison Rose",
    date: "Sat, Jun 25, 18:00",
  },
  {
    id: 3,
    city: "Istanbul",
    image: "/res_3.png",
    people: "2 people",
    price: "$$",
    category: "Guest Favorite",
    name: "Gümrük",
    date: "Sat, Jun 25, 19:30",
  },
  {
    id: 4,
    city: "Prague",
    image: "/res_1.png",
    people: "2 people",
    cuisine: "Italian",
    price: "$$",
    category: "Green Oasis",
    name: "Le Chat Blanc",
    date: "Sat, Jun 25, 17:00",
  },
  {
    id: 5,
    city: "Paris",
    image: "/res_2.png",
    people: "2 people",
    cuisine: "Italian",
    price: "$$",
    category: "Green Oasis",
    name: "Le Chat Blanc",
    date: "Sat, Jun 25, 17:00",
  },
  {
    id: 6,
    city: "Paris",
    image: "/res_3.png",
    people: "2 people",
    cuisine: "Italian",
    price: "$$",
    category: "Green Oasis",
    name: "Le Chat Blanc",
    date: "Sat, Jun 25, 17:00",
  },
];
